services:
  postgres:
    image: postgres:17
    container_name: studentdb
    restart: unless-stopped
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - studentdb:/var/lib/postgresql/data

volumes:
    studentdb:
