= Digitale Schulwahlplattform
Antonio Subašić, Flora Dallinger, Sarah Ngimbi, Elysee Mbala
3ahif
:toc: left
:toclevels: 3
:sectnums:
:imagesdir: ./images

== Pflichtenheft "Was mache ich"

=== Ausgangssituation

Die HTL Leonding ist eine höhere technische Lehranstalt in Leonding, Oberösterreich mit etwa 1000 Schülerinnen und Schülern.
Sie bietet Ausbildungen in verschiedenen Fachrichtungen wie Informatik, Medientechnik, Elektronik und Medizintechnik an.


=== Istzustand

Seit vielen Jahren werden die Wahlen der Schülervertretung in Papierform durchgeführt.
Sowohl die Stimmenabgabe als auch die Auszählung der Stimmen erfolgt per Hand. Dieser Prozess ist zeitaufwendig und fehleranfällig.

=== Problemstellung

Der bisherige Wahlprozess ist ineffizient und fehleranfällig. Außerdem werden viele Ressourcen wie z.B. Papier und Arbeitszeit übermäßig
benötigt.

=== Aufgabenstellung

Die Entwicklung einer Schulwahlplattform, die Stimmenabgabe, -auszählung und -validierung digitalisiert.
Die digitale Lösung soll die Wahlen vereinfachen, beschleunigen und fehlerresistenter machen.


==== Funktionale Anforderungen
Zuerst werden Codes für die Klassen generiert. Hierbei kommt es schon zur ersten Funktionalität. Anschließend sollen sich auf der Schulwahlplattform sowohl Schülerinnen und Schüler als auch Lehrkräfte einloggen können.
Danach soll man als Lehrperson die jeweilige Klasse und die Anzahl der anwesenden Schülerinnen und Schüler angeben können.
Mit den Klassencode können sich schlussendlich die Wählenden einloggen und mit dem ihnen zugewiesenen eigenen Code fortfahren.
Sobald dies geschehen ist, finden diese eine Liste der Kandidierenden vor.
In diese können sie nun jeweils einen Block mit einer Punkteanzahl abgeben. +
Zum Schluss soll noch eine Möglichkeit zum Abschluss der Stimmenabgabe zur Verfügung stehen.

.Übersicht
* Generierung eines Codes pro Klasse
* Eingabe der Kandidierenden
* Als Lehrkraft einloggen
** Auswahl der Klasse
** Auswahl der präsenten Lernenden
** Wahl schließen
* Als Wählende mit dem Code der Klasse einloggen
** Stimmen zuteilen mit Hilfe von Punkte-Blöcken
** Abgabe Button

==== Nicht-Funktionale Anforderungen
* Anonymes Wählen
* Robustheit (ca. 1000 Wahlen auf einmal)
* Einhaltung rechtlicher Rahmenbedingungen

=== Ziele
.Wirkungsziele
* Vereinfachung und Automatisierung des Wahlprozesses
** Steigerung der Effizienz
** Reduzierung von Fehlern
* Beschleunigung des Wahlprozesses
* Reduzierung des Papierverbrauchs

.Nicht-Ziele
* Verwaltung von der Liste der Schülerinnen und Schüler
* Verwaltung von Klassenlisten
* Plausibilitätsprüfungen

=== Mengengerüst

Die Wahl für die Schülervertretung findet einmal im Jahr statt.
Einzurechnen sind dabei ca. 1000 Wählerinnen und Wähler, die alle am selben Tag innerhalb kurzer Zeit abstimmen wollen. Dabei müssen diese
jeweils maximal 6 Punkte-Blöcke abgeben.

=== Rahmenbedingungen
Es müssen sowohl rechtliche als auch organisatorische Rahmenbedingungen eingehalten werden. Zu den rechtlichen Rahmenbedingungen zählt,
dass alle Wählerinnen und Wähler anonym wählen und nur einmal ihre Stimme abgeben können. +
Organisatorisch muss sichergestellt werden, dass die Software im Schulnetzwerk eingebunden ist und für die Dauer der Wahl nur den beteiligten
Lehrkräften und Lernende zur Verfügung steht. +
Eine Betreuung und Wartung durch einen Systemadministrator ist für die Folgejahre erforderlich.


