= Digitale Schulwahlplattform
Antonio Subašić, Flora Dallinger, Sarah Ngimbi, Elysee Mbala
:toc: left
:toclevels: 3
:sectnums:
:imagesdir: ./images

== Pflichtenheft "Was mache ich"

=== Ausgangssituation

Die HTL Leonding ist eine höhere technische Lehranstalt (HTL) in Leonding, Oberösterreich mit etwa 1000 Schüler*innen.
Sie bietet Ausbildungen in verschiedenen Fachrichtungen wie Informatik, Medientechnik, Elektronik und Medizintechnik an.


=== Istzustand

Seit vielen Jahren werden die Wahlen der Schülersprecher*innen und Stellvertreter*innen in Papierform durchgeführt.
Sowohl die Stimmenabgabe als auch die Auszählung der Stimmen erfolgt per Hand. Dieser Prozess ist zeitaufwendig und fehleranfällig.

=== Problemstellung

Der bisherige Wahlprozess ist ineffizient und fehleranfällig. Außerdem werden viele Ressourcen wie z.B. Papier und Arbeitszeit übermäßig
benötigt.

=== Aufgabenstellung

Die Entwicklung einer Schulwahlplattform, die Stimmenabgabe, -auszählung und -validierung digitalisiert.
Die digitale Lösung soll die Wahlen vereinfachen, beschleunigen und fehlerresistenter machen.



==== Funktionale Anforderungen
Auf der Schulwahlplattform sollen sich sowohl Schüler*innen als auch Lehrer*innen einloggen können. Hierbei kommt es schon zur ersten Funktionalität.
Danach soll man als Lehrer die jeweilige Klasse und die Anzahl der anwesenden Schüler*innen angeben können.
Als nächstes werden Codes generiert. +
Mit diesen Codes können sich schlussendlich die Schüler*innen einloggen. Sobald dies geschehen ist, finden diese eine Liste der kandidierenden Schüler*innen vor.
In diese können sie nun jeweils einen Block mit einer Punkteanzahl abgeben. +
Zum Schluss soll noch eine Möglichkeit zum Abschluss der Stimmenabgabe zur Verfügung stehen.

.Übersicht
* Als Lehrer*in einloggen
** Auswahl der KLasse
** Auswahl der präsenten Schüler*innen
** Generierung eines Codes
* Als Schüler*in einloggen mit einem Code
** Stimmen zuteilen mit Hilfe von Punkte-Blöcken
** Abgabe Button

==== Nicht-Funktionale Anforderungen
* Anonymes Wählen
* Robustheit (ca. 1000 Wahlen auf einmal)
* Einhaltung rechtlicher Rahmenbedingungen

=== Ziele
.Wirkungsziele
* Vereinfachung und Automatisierung des Wahlprozesses
** Steigerung der Effizienz
** Reduzierung von Fehlern
* Beschleunigung des Wahlprozesses
* Reduzierung des Papierverbrauchs

.Nicht-Ziele
* Verwaltung von Schüler*innenlisten
* Verwaltung von Klassenlisten
* Plausilibitätsprüfungen

=== Mengengerüst

Die Wahl für die Schülervertretung findet einmal im Jahr statt.
Einzurechnen sind dabei ca. 1000 Schüler*innen, die alle am selben Tag innerhalb kurzer Zeit abstimmen wollen. Dabei müssen diese
jeweils maximal 8 Punkte-Blöcke abgeben.

=== Ramenbedingungen
Es müssen sowhol rechtliche als auch organisatorische Ramenbedingungen eingehalten werden. Zu den rechtlichen Ramenbedingungen zählt,
dass jede*r Schüler*in anonym wählen und nur ein Mal seine/ihre Stimme abgeben kann. +
Organisatorisch muss sichergestellt werden, dass die Software im Schulnetzwerk eingebunden ist und für die Dauer der Wahl nur den Beteiligten
Lehrer*innen und Schüler*innen zur Verfügung steht. +
Eine Betreuung und Wartung durch einen Systemadministrator ist für die Folgejahre erforderlich.

