= Digitale Schulwahlplattform
Antonio Subašić, Flora Dallinger, Sarah Ngimbi, Elysee Mbala
:toc: left
:toclevels: 3
:sectnums:
:imagesdir: ./images

== Pflichtenheft "Was mache ich"

=== Ausgangssituation

Die HTL Leonding ist eine technische Schule in Leonding, Oberösterreich mit etwa 1000 Schüler*innen. Sie bietet verschiedene Fachrichtungen wie Informatik, Medientechnik, Elektronik und Medizintechnik an.

=== Istzustand

Seit vielen Jahren werden die Wahlen der Schülersprecher*innen und Stellvertreter*innen in Papierform durchgeführt.
Sowohl die Stimmenabgabe als auch die Auszählung der Stimmen erfolgt per Hand. Dieser Prozess ist zeitaufwendig und fehleranfällig.

=== Problemstellung

Der bisherige Wahlprozess ist ineffizient und fehleranfällig. Die digitale Lösung soll die Wahlen vereinfachen, beschleunigen und fehlerresistenter machen.

=== Aufgabenstellung

Die Entwicklung einer Schulwahlplattform, die Stimmenabgabe, -auszählung und -validierung digitalisiert.

==== Funktionale Anforderungen
Auf der Schulwahlplattform sollen sich sowohl Schüler*innen als auch Lehrer*innen einloggen können. Hierbei kommt es schon zur ersten Funktionalität.
Danach soll man als Lehrer die jeweilige Klasse und die Anzahl der anwesenden Schüler*innen angeben können.
Als nächstes werden Codes generiert. +
Mit diesen Codes können sich schlussendlich die Schüler*innen einloggen. Sobald dies geschehen ist, finden diese eine Liste der kandidierenden Schüler*innen vor.
In diese können sie nun jeweils einen Block mit einer Punkteanzahl abgeben. +
Zum Schluss soll noch ein Button für die Abgabe zur Verfügung stehen.

* Als Lehrer*in einloggen
** Auswahl der KLasse
** Auswahl der präsenten Schüler*innen
** Generierung eines Codes
* Als Schüler*in einloggen mit einem Code
** Stimmen zuteilen mit Hilfe von Punkte-Blöcken
** Abgabe Button

==== Nicht-Funktionale Anforderungen
* Anonymes wählen
* Robust (ca. 1000 Wahlen auf einmal)
* Rechtlichen Richtlinien entsprechen

=== Ziele

* Vereinfachung und Automatisierung des Wahlprozesses
* Steigerung der Effizienz
* Reduzierung von Fehlern
* Beschleunigung des Wahlprozesses
* Reduzierung des Papierverbrauchs

=== Mengengerüst

Die Wahl für die Schülervertretung findet einmal im Jahr statt.
Einzurechnen sind dabei ca. 1000 Schüler*innen, die alle am selben Tag abstimmen wollen. Dabei müssen diese
jeweils maximal 8 Stimmen abgeben. +
Je nachdem wie viele Schüler*innen für einen Posten kandidieren können die zu wählenden Schüler*innen und somit auch die abzugebenden Stimmen variieren.


