= Digitale Schulwahlplattform
Antonio Subašić, Flora Dallinger, Sarah Ngimbi, Elysee Mbala
:toc: left
:toclevels: 3
:sectnums:

== Pflichtenheft "Was mache ich"

=== Ausgangssituation

Die HTL Leonding ist eine technische Schule in Leonding, Oberösterreich mit etwa 1000 Schüler*innen. Sie bietet verschiedene Fachrichtungen wie Informatik, Medientechnik, Elektronik und Medizintechnik an.

=== Istzustand

Seit vielen Jahren werden die Wahlen der Schülersprecher*Innen und Stellvertreter*Innen in Papierform durchgeführt.
Sowohl die Stimmenabgabe als auch die Auszählung der Stimmen erfolgt per Hand. Dieser Prozess ist zeitaufwendig und fehleranfällig.

=== Problemstellung

Der bisherige Wahlprozess ist ineffizient und fehleranfällig. Die digitale Lösung soll die Wahlen vereinfachen, beschleunigen und fehlerresistenter machen.

=== Aufgabenstellung

Die Entwicklung einer Schulwahlplattform, die Stimmenabgabe, -auszählung und -validierung digitalisiert.

//TODO: Funktionale Anforderungen + Nicht-funktionale Anforderungen kontrollieren und absprechen
//TODO: Ausformulierung der Stichpunkte
==== Funktionale Anforderungen
Auf der Schulwahlplattform sollen sich sowohl Sch

* Als Lehrer*In einloggen
** Auswahl der KLasse
** Auswahl der präsenten Schüler*innen
** Generierung eines Codes
* Als Schüler*In einloggen mit einem Code
** Stimmen zuteilen mit Hilfe von Punkte-Blöcken

==== Nicht-Funktionale Anforderungen
* Anonymes wählen
* Robust (ca. 1000 Wahlen auf einmal)
* Rechtlichen Richtlinien entsprechen

=== Ziele

* Vereinfachung und Automatisierung des Wahlprozesses
* Reduzierung von Fehlern
* Beschleunigung des Wahlprozesses
* Reduzierung des Papierverbrauchs

=== Mengengerüst

Einzurechnen sind ca. 1000 Schüler*innen, die alle auf einmal abstimmen wollen. Dabei müssen diese
jeweils maximal 8 Stimmen abgeben.
Je nach Aufstellung können die zu wählenden Schüler*innen und somit auch die abzugebenden Stimmen variieren.

* 1000 Schüler*innen
* 8 abzugebende Stimmen pro Schüler*in
* 1 Wahl pro Jahr
