name: Build and Release
run-name: ${{ github.actor }} is releasing the newest version.

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Build with Maven
        run: |
          pushd javafx
            mvn clean package
          popd

          mkdir -p dist
          cp -r javafx/target/digitale-schulwahl-*.jar dist/app.jar

      - name: Get the git commits since the last tag
        run: |
          echo "$(git log $(git describe --tags --abbrev=0)..HEAD | git shortlog)" | sed 's/^ \+/- /' > release-notes.txt
          cat release-notes.txt

      - name: Release the build
        run: |
          tag="${{ github.ref_name }}"
          gh release create $tag \
            ./dist/app.jar \
            --title "Digitale Schulwahl $tag" \
            --notes-file release-notes.txt \
            --draft=false \
            --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
